---

- hosts: all
  become: yes
  pre_tasks:

  - name: update repository index
    tags: always
    apt: 
      update_cache: yes

- hosts: webserver
  become: true
  tasks:
  - name: install apache2 for debian
    tags: apache2
    apt:
      name: 
        - apache2
  
  - name: install certificates
    tags: php,certificates
    apt: 
      update_cache: true
      name: 
        - gnupg2
        - lsb-release
        - ca-certificates
        - apt-transport-https
        - software-properties-common
        - wget
   
  # - name: import repository key
  #   tags: php,phprepokey
  #   get_url: 
  #     url:  https://packages.sury.org/php/apt.gpg
  #     dest: /etc/apt/trusted.gpg.d/php.gpg

  # - name: add php packages apt repository to debian server
  #   tags: php
  #   command: echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/sury-php.list

  - name: add repo into sources list
    tags: php,repository
    # become: no
    apt_repository:
      repo:  ppa:ondrej/php


  - name: update repository index
    apt:
      update_cache: true

  - name: install php
    tags: php,repository
    apt:    
      update_cache: true  
      name: php8.0
               
  - name: install php extensions and git
    tags: php,php-extensions
    apt:
      name:
        - php8.0-cgi
        - php8.0-common
        - php8.0-curl
        - php8.0-dev
        - php8.0-gd
        - php8.0-fpm
        - php8.0-cli
        - php8.0-dba
        - php8.0-gmp
        - php8.0-imap
        - php8.0-intl
        - php8.0-ldap
        - php8.0-enchant
        - php8.0-mysql
        - php8.0-odbc
        - php8.0-phpdbg
        - php8.0-pspell
        - php8.0-readline
        - php8.0-tidy
        - php8.0-xsl
        - php8.0-zip
        - php8.0-soap
        - php8.0-xml
        - git

  - name: copy postgres folder to server
    tags: postgres
    copy:
      src: db/
      dest: /home/ubuntu/db/
  
  - name: change script permission
    tags: postgres,permission
    file:
      path: /home/ubuntu/db/psql_install.sh
      mode: 0755
  
  - name: run postgres shell
    tags: postgres
    shell: ./psql_install.sh
    args:
      chdir: /home/ubuntu/db/

  
  - name: install composer
    tags: composer
    shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    args:
      creates: /usr/local/bin/composer
  
  
  - name: install composer on ansible controller
    tags: composer
    connection: local
    package:
      name: composer
      state: present


  